version: '3.6'

services:
  web:
    hostname: web
    build:
      context: ./
      dockerfile: ./docker/django/Dockerfile
    container_name: web
    volumes:
      - .:/app
    command: python /app/src/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    networks:
    - net

networks:
  net: