version: '3.6'

volumes:
  database_data:
    driver: local

networks:
  net:

services:
  web:
    hostname: web
    build:
      context: ./
      dockerfile: ./docker/django/Dockerfile
    container_name: web
    volumes:
      - .:/app
    command: python /app/src/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    networks:
    - net
    depends_on:
    - db

  db:
    image: postgres:10.1
    restart: always
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw
    ports:
    - 5432:5432
    volumes:
    - database_data:/var/lib/postgresql/data
    networks:
    - net
